/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./apps/**/templates/**/*.html",
    "./static/js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c2c7cc",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf9fa",
        "on-primary": "#ffffff",
        "background": "#faf9fa",
        "on-error-container": "#93000a",
        "on-primary-container": "#e7ebff",
        "inverse-primary": "#b1c5ff",
        "surface-container-high": "#e9e8e9",
        "on-secondary-container": "#606569",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d5",
        "surface-variant": "#e3e2e3",
        "tertiary-container": "#bfab49",
        "primary-fixed-dim": "#b1c5ff",
        "surface-container-highest": "#e3e2e3",
        "on-primary-fixed": "#001946",
        "on-tertiary-fixed": "#211b00",
        "tertiary-fixed": "#f9e37a",
        "primary": "#094cb2",
        "on-surface-variant": "#434653",
        "surface-container-low": "#f5f3f4",
        "on-background": "#1b1c1d",
        "primary-fixed": "#d9e2ff",
        "inverse-on-surface": "#f2f0f1",
        "surface-container": "#efedee",
        "error-container": "#ffdad6",
        "tertiary": "#6d5e00",
        "inverse-surface": "#303031",
        "on-tertiary-container": "#4a3f00",
        "surface-dim": "#dbdadb",
        "on-primary-fixed-variant": "#00419d",
        "surface": "#faf9fa",
        "on-surface": "#1b1c1d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#171c20",
        "surface-tint": "#2259bf",
        "outline": "#737784",
        "secondary-container": "#dfe3e8",
        "tertiary-fixed-dim": "#dcc661",
        "secondary": "#5a5f63",
        "primary-container": "#3366cc",
        "on-tertiary-fixed-variant": "#524600",
        "error": "#ba1a1a",
        "secondary-fixed": "#dfe3e8",
        "on-secondary-fixed-variant": "#42474b"
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      fontFamily: { headline: ["Noto Serif"], display: ["Noto Serif"], body: ["Inter"], label: ["Public Sans"] }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
