# Generated by Django 6.1.1 on 2026-09-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domain', models.CharField(choices=[('web-django', 'Pengembangan Web (Django/Tailwind)'), ('security-audit', 'Audit & Konsultasi Keamanan'), ('data-analysis', 'Analisis & Visualisasi Data'), ('academic', 'Undangan Diskusi / Kolaborasi Akademik'), ('other', 'Eksplorasi Ide / Diskusi Lainnya')], default='web-django', max_length=20)),
                ('timeline', models.CharField(choices=[('fleksibel', 'Jadwal Fleksibel / Tahap Eksplorasi'), ('segera', 'Segera (1-4 Minggu ke Depan)'), ('q2-2025', 'Kuartal Q2 (Apr - Jun 2025)'), ('q3-2025', 'Kuartal Q3 (Jul - Sep 2025)')], default='fleksibel', max_length=20)),
                ('scope', models.CharField(choices=[('akademik', 'Riset Terbuka / Institusi Pendidikan'), ('mvp', '< IDR 5M (Protipe MVP / Audit Skala Kecil)'), ('growth', 'IDR 5M - 15M (Sistem Penuh / Dashboard)'), ('enterprise', '> IDR 15M (Infrastruktur Komprehensif)')], default='akademik', max_length=20)),
                ('message', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
    ]
