# Generated by Django 6.1.1 on 2026-09-19 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AREYBRA', max_length=50)),
                ('tagline', models.CharField(default='Desainer Produk & Creative Technologist', max_length=120)),
                ('hero_name', models.CharField(default='Areta Y. Radjawali', max_length=100)),
                ('hero_title', models.CharField(default='Junior Web Development', max_length=100)),
                ('hero_description', models.TextField(default='Membangun sistem digital terukur, kejernihan arsitektur antarmuka, dan pengalaman web visceral yang dirancang pada titik temu keindahan estetika dan presisi rekayasa kode.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='aretaradjawali@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='6282142961010', help_text='Format 62 tanpa + (contoh 6282142961010)', max_length=20, validators=[django.core.validators.RegexValidator('^62\\d{9,14}$', 'Format 62xxxxxxxxxxx')])),
                ('location', models.CharField(default='Kabupaten Probolinggo & Jawa Timur', max_length=100)),
                ('timezone_label', models.CharField(default='WIB (UTC+7) · Jakarta, Indonesia', max_length=50)),
                ('availability_text', models.CharField(default='Tersedia untuk proyek baru Q2/Q3 2025', max_length=120)),
                ('availability_active', models.BooleanField(default=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('footer_description', models.TextField(default='Studio desain produk independen yang memadukan keanggunan tipografi editorial, arsitektur perangkat lunak presisi, dan filosofi interaksi modern.')),
                ('about_quote', models.TextField(blank=True, default='"Berasal dari Kab. Probolinggo, kini menempuh pendidikan SLTA di SMK Nurul Jadid dalam bidang keahlian Rekayasa Perangkat Lunak. Selain meminati Web Development juga tertarik dengan Cyber Security."')),
                ('about_vision', models.TextField(blank=True, default='Menjadi arsitek solusi digital dan Data Analyst yang mampu mengurai kompleksitas data menjadi keputusan bernilai, aman dari celah siber.')),
                ('github_username', models.CharField(default='aretaradjawali', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('dribbble_url', models.URLField(blank=True, default='https://dribbble.com')),
                ('readcv_url', models.URLField(blank=True, default='https://read.cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Material symbol', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.siteprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.siteprofile')),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='dns', max_length=30)),
                ('domain_label', models.CharField(default='Domain 01', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tools_text', models.CharField(blank=True, help_text='Postman, Docker, Git Bash', max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='core.siteprofile')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=150)),
                ('icon', models.CharField(default='code', max_length=30)),
                ('level', models.CharField(choices=[('mahir', 'Mahir'), ('kompeten', 'Kompeten'), ('menengah', 'Menengah'), ('riset', 'Riset Aktif'), ('aspirasi', 'Aspirasi Utama')], default='kompeten', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('dribbble', 'Dribbble'), ('readcv', 'Read.cv'), ('email', 'Email'), ('telegram', 'Telegram/WA'), ('other', 'Other')], default='github', max_length=20)),
                ('label', models.CharField(help_text='Contoh: GitHub / @aretaradjawali', max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='Material Symbol name, ex: code, work', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.siteprofile')),
            ],
            options={
                'verbose_name': 'Social Link',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(help_text='Pilar I / II', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='flag', max_length=30)),
                ('footer_label', models.CharField(blank=True, max_length=50)),
                ('footer_value', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='primary', help_text='primary / tertiary', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='core.siteprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
