# Generated by Django 6.1.1 on 2026-09-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteprofile_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_image_url',
            field=models.URLField(blank=True, default='https://lh3.googleusercontent.com/aida/AEtjO1UEoiyjmRKUBIc9t_Fndn02qah9zD4YxMOclwvCsw3RgF04tBa7qBJtB3e-J04xQLKcvUDjFs3W9OGpRH2ONio9YqP3AFOlbnf_VADprquwDe9nBnqaSBN4w2LlKcPBqpkEODL3pzu4GkgxG44ucGQRBvUR2HQGWMBjGgDsHFLRA1U1NAfAjAKRmAirn9ZaUcwEP-OH1rfpqF-1S_JV3Za18csDTh8B6C7BX43cPLUS05jJpemociIHRQPo', help_text='URL gambar profil (gunakan URL eksternal untuk hemat storage, mis. https://...)', max_length=500, verbose_name='Foto Profil URL'),
        ),
    ]
