# Generated by Django 6.1.1 on 2026-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL cover artikel (eksternal).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='blog/%Y/'),
        ),
    ]
