# Generated by Django 6.1.1 on 2026-09-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(help_text='Deskripsi lengkap studi kasus')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/%Y/')),
                ('mock_type', models.CharField(blank=True, help_text='kroma / aura / chronos etc for SVG placeholder', max_length=30)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('reference_code', models.CharField(blank=True, help_text='#KRM-01', max_length=30)),
                ('featured', models.BooleanField(default=False, help_text='Tampil di landing hero/spotlight')),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('is_spotlight', models.BooleanField(default=False, help_text='Spotlight di halaman proyek (Kroma OS)')),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2)),
                ('rating_count', models.CharField(default='8.1k', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text='Healthtech Core / Security Tooling', max_length=80)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.category')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology')),
            ],
            options={
                'ordering': ['-featured', 'featured_order', '-created_at'],
            },
        ),
    ]
