# Generated by Django 6.1.1 on 2026-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL gambar thumbnail (eksternal, hemat storage). Kosongkan untuk pakai placeholder SVG.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='projects/%Y/'),
        ),
    ]
